import{a as h,S as g,i as s}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const b="44428649-a15122ccea82814442a666457",L="https://pixabay.com/api/";async function m(e,o=1,i=15){return(await h.get(L,{params:{key:b,q:e,image_type:"photo",page:o,per_page:i}})).data}function u(e,o){if(!Array.isArray(e)){console.error("Expected images to be an array, but got:",e);return}const i=e.map(t=>`
    <li>
      <a href="${t.largeImageURL}" class="gallery-item">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy">
        <div class="info">
          <p class="info-item"><b>Likes</b> ${t.likes}</p>
          <p class="info-item"><b>Views</b> ${t.views}</p>
          <p class="info-item"><b>Comments</b> ${t.comments}</p>
          <p class="info-item"><b>Downloads</b> ${t.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");o.insertAdjacentHTML("beforeend",i),n&&n.destroy();const n=new g(".gallery a",{captionsData:"alt",captionDelay:250});n.refresh()}function E(e){e.innerHTML=""}function y(){const e=document.getElementById("loader");e?e.classList.remove("hidden"):console.error("Loader element not found.")}function p(){const e=document.getElementById("loader");e?e.classList.add("hidden"):console.error("Loader element not found.")}function B(){const e=document.getElementById("load-more-btn");e?e.classList.remove("hidden"):console.error("Load more button element not found.")}function f(){const e=document.getElementById("load-more-btn");e?e.classList.add("hidden"):console.error("Load more button element not found.")}const w=document.querySelector("#search-form"),d=document.getElementById("gallery");document.getElementById("loader");const v=document.getElementById("load-more-btn");let l="",a=1;f();w.addEventListener("submit",async e=>{if(e.preventDefault(),l=e.target.elements.searchQuery.value.trim(),!l){s.error({title:"Error",message:"Search query cannot be empty!"});return}a=1,E(d),f(),destroyLightbox(),y();try{const o=await m(l,a);o.hits.length===0?s.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(u(o.hits,d),o.totalHits>a*15&&B())}catch(o){console.error(o),s.error({title:"Error",message:"Failed to fetch images!"})}finally{p()}});v.addEventListener("click",async()=>{a+=1,y();try{const e=await m(l,a);u(e.hits,d),a*15>=e.totalHits&&(f(),s.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.error(e),s.error({title:"Error",message:"Failed to fetch images!"})}finally{p()}});console.log("iziToast loaded:",typeof s<"u");console.log("SimpleLightbox loaded:",typeof SimpleLightbox<"u");
//# sourceMappingURL=commonHelpers.js.map
