import{a as h,S as g,i as s}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="44428649-a15122ccea82814442a666457",L="https://pixabay.com/api/";async function m(t,r=1,a=15){return(await h.get(L,{params:{key:b,q:t,image_type:"photo",page:r,per_page:a}})).data}function u(t,r){if(!Array.isArray(t)){console.error("Expected images to be an array, but got:",t);return}const a=t.map(e=>`
    <li>
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
        <div class="info">
          <p class="info-item"><b>Likes</b> ${e.likes}</p>
          <p class="info-item"><b>Views</b> ${e.views}</p>
          <p class="info-item"><b>Comments</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
        </div>
      </a>
    </li>
  `).join("");r.insertAdjacentHTML("beforeend",a),new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function E(t){t.innerHTML=""}function y(){const t=document.getElementById("loader");t?t.classList.remove("hidden"):console.error("Loader element not found.")}function p(){const t=document.getElementById("loader");t?t.classList.add("hidden"):console.error("Loader element not found.")}const v=document.querySelector("#search-form"),f=document.getElementById("gallery");document.getElementById("loader");const c=document.getElementById("load-more-btn");let l="",n=1;v.addEventListener("submit",async t=>{if(t.preventDefault(),l=t.target.elements.searchQuery.value.trim(),!l){s.error({title:"Error",message:"Search query cannot be empty!"});return}n=1,E(f),c.classList.add("hidden"),y();try{const r=await m(l,n);r.hits.length===0?s.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):(u(r.hits,f),r.totalHits>n*15&&c.classList.remove("hidden"))}catch(r){console.error(r),s.error({title:"Error",message:"Failed to fetch images!"})}finally{p()}});c.addEventListener("click",async()=>{n+=1,y();try{const t=await m(l,n);u(t.hits,f),n*15>=t.totalHits&&(c.classList.add("hidden"),s.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}))}catch(t){console.error(t),s.error({title:"Error",message:"Failed to fetch images!"})}finally{p()}});console.log("iziToast loaded:",typeof s<"u");console.log("SimpleLightbox loaded:",typeof SimpleLightbox<"u");
//# sourceMappingURL=commonHelpers.js.map
